w3c/clipboard-apis

- index.html
>  This logic depends on factors like whether the cursor is in an editable context (for paste commands) or whether there is a selection (for copy commands).
I think it would be good to add logic for cut commands:
>  This logic depends on factors like whether the cursor is in an editable context (for paste commands), whether there is a selection (for copy commands), or where there is a selection within an editable context  (for cut commands).
> Expand explanation of UI state logic

- .travis.yml
I've been told this spec is transitioning from ReSpec to Bikeshed. While it does, [commits are still triggering automatic publication, and always failing](https://www.w3.org/Search/Mail/Public/search?keywords=&hdr-1-name=subject&hdr-1-query=clipboard-apis&index-grp=Public_FULL&index-type=t&type-index=public-tr-notifications).
Avoid calling Echidna until the repo is set up to submit a valid WD again.
cf #36
> Pause automatic publication for now

- index.bs
- index.html
This change updates wording in Algorithms section (6) to accurately reflect on what should actually happen to target selection in non-edtiable
contexts.
https://github.com/w3c/clipboard-apis/issues/40
> Pull request for Issue #40

- explainer.adoc
The callback/listener distinction is not very important, changes really
done to avoid the wording "new event listener", as it's a new event type.
See https://dom.spec.whatwg.org/#concept-event-listener
> Nitpick terminology around events in explainer

- index.bs
This change addresses the ambiguity of unfocused and hidden
selections (#57) by stating that only a visible selection can be a
ClipboardEvent-target.
> Emphasize visability in the "pick target"-algorithm

- index.bs
This resolves https://github.com/w3c/clipboard-apis/issues/61
> Make all clipboard events composed by default.

- index.bs
This was previously only done for the `read` method, this patch adds it to `readText`, `write` and `writeText` as well.
Fixes #76
> Specify NotAllowedError when permission is not granted

- index.bs
That MICROSOFT-CLIP-OP reference is quite obsolete... maybe consider removing it entirely?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/pull/90.html" title="Last updated on May 21, 2019, 8:20 PM UTC (6e5c7ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/90/4874398...6e5c7ae.html" title="Last updated on May 21, 2019, 8:20 PM UTC (6e5c7ae)">Diff</a>
> Fixup some references

- tidyconfig.txt
Hi! While working on [this PR](https://github.com/w3c/clipboard-apis/pull/109), I noticed that there is no `tidyconfig.txt` 
I used the tidyconfig from the [Payment Request spec](https://github.com/w3c/payment-request/blob/gh-pages/tidyconfig.txt).
cc @marcoscaceres
> Chore: Add tidyconfig to spec

- index.bs
- index.html
The current example doesn't match the specification (taking an array of `ClipboardItem`s), and doesn't work in e.g. Chrome.
I've updated it so that it matches the spec, which makes it work in Chrome.
(I've also fixed some smart quotes so this works correctly if it's copied and pasted.)
The following tasks have been completed:
***
<a href="https://pr-preview.s3.amazonaws.com/lgarron/clipboard-apis/pull/111.html" title="Last updated on Feb 28, 2020, 9:36 PM UTC (580a0eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/111/897bbff...lgarron:580a0eb.html" title="Last updated on Feb 28, 2020, 9:36 PM UTC (580a0eb)">Diff</a>
> Update `clipboard.write()` example to use a `ClipboardItem` list.

- index.html
- tests.html
Hi! I recently [imported](https://github.com/whatwg/html/pull/5253/) the definition of `editing host` from the execCommand spec to the HTML spec.
@marcoscaceres mentioned that the next steps are to find other specs that currently use `editing host` and to do the following:
1. remove any redefinitions
2. link the singular and plural forms of `editing host` to the [current definition in the HTML spec](https://html.spec.whatwg.org/multipage/interaction.html#editing-host).
In this PR, I have :
1. removed a redefinition of `editing host` that links to https://dvcs.w3.org/hg/editing/raw-file/tip/editing.html#editing-host
2. linked `editing host` to the current definition in the HTML spec.
Similar PRs related to the `editing host` import:
* [PR 108 - Input …
> Editorial: Remove redefinition of `editing host`. Link mentions of it to its HTML spec definition

- index.bs
Closes https://github.com/w3c/webappswg/issues/34
The following tasks have been completed:
* [x ] Confirmed there are no ReSpec/BikeShed errors or warnings.
* [x ] Modified Web platform tests (link to pull request)
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 3, 2020, 6:25 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fclipboard-apis%2Fpull%2F118%2F850b84d.h …
> Update the previous version

- index.bs
Closes #146
***
<a href="https://pr-preview.s3.amazonaws.com/mfalken/clipboard-apis/pull/147.html" title="Last updated on May 23, 2021, 8:20 AM UTC (4515668)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/147/5b75462...mfalken:4515668.html" title="Last updated on May 23, 2021, 8:20 AM UTC (4515668)">Diff</a>
> Add link-default for HTML's Navigator interface.

- explainer.adoc
- index.bs
Images are only sanitized when writing to the clipboard, not when
reading them back. This is consistent with the Firefox and Safari
implementations, while Chrome also plans to match this behavior.
This is merely clarifying spec language. Before the spec was silent on
transcoding images on read, while now we make it explicit that not
transcoding should be done.
***
<a href="https://pr-preview.s3.amazonaws.com/mkruisselbrink/clipboard-apis/pull/156.html" title="Last updated on Sep 7, 2021, 9:09 PM UTC (669d8b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/156/71c9405...mkruisselbrink:669d8b7.html" title="Last updated on Sep 7, 2021, 9:09 PM UTC (669d8b7)">Diff</a>
> Add explicit language around (not) sanitizing images.

- index.bs
Spec errors in #158
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 8, 2022, 6:53 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fclipboard-apis%2F974e63cb1392ea12b434e3df6b761b5ff1e211ac%2Findex.bs&force=1&md-warning=not%20ready)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The …
```
> Fix spec errors due to invalid markup.

- index.bs
Closes #150 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/pull/174.html" title="Last updated on May 20, 2022, 6:50 PM UTC (467a4e6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/174/14c72dc...467a4e6.html" title="Last updated on May 20, 2022, 6:50 PM UTC (467a4e6)">Diff</a>
> Remove sanitize copy requirement from the spec.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/clipboard-apis/pull/181.html" title="Last updated on Jul 7, 2022, 8:41 AM UTC (bbdaf6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/181/50fa9c4...dontcallmedom:bbdaf6f.html" title="Last updated on Jul 7, 2022, 8:41 AM UTC (bbdaf6f)">Diff</a>
> Mark up definition of events following bikeshed conventions

- index.bs
Closes #165 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/pull/175.html" title="Last updated on Sep 18, 2023, 6:34 PM UTC (c6394d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/175/4db562e...c6394d3.html" title="Last updated on Sep 18, 2023, 6:34 PM UTC (c6394d3)">Diff</a>
> Add Web Custom format

- index.bs
Closes https://github.com/w3c/editing/issues/412
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/pull/194.html" title="Last updated on Sep 18, 2023, 9:47 PM UTC (1708924)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/194/eb4e99a...1708924.html" title="Last updated on Sep 18, 2023, 9:47 PM UTC (1708924)">Diff</a>
> Update custom types on Mac.

- index.bs
Closes https://github.com/w3c/clipboard-apis/pull/175#discussion_r1329392888
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/pull/195.html" title="Last updated on Oct 24, 2023, 8:29 PM UTC (e3ae9c5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/195/39b067c...e3ae9c5.html" title="Last updated on Oct 24, 2023, 8:29 PM UTC (e3ae9c5)">Diff</a>
> Add 'starts with' to web custom format prefix.

- index.bs
Closes #????
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/pull/197.html" title="Last updated on Nov 18, 2023, 1:29 AM UTC (0312e3e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/197/ad65071...0312e3e.html" title="Last updated on Nov 18, 2023, 1:29 AM UTC (0312e3e)">Diff</a>
> Add `unsanitized` option to async clipboard API.

- index.bs
Closes #206 
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/pull/208.html" title="Last updated on Feb 6, 2024, 6:36 PM UTC (63dac66)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/208/c1d37ae...63dac66.html" title="Last updated on Feb 6, 2024, 6:36 PM UTC (63dac66)">Diff</a>
> Add non-normative and optional texts.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/siusin/clipboard-apis/pull/234.html" title="Last updated on Mar 18, 2025, 10:36 AM UTC (7087ea6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/234/2eebe17...siusin:7087ea6.html" title="Last updated on Mar 18, 2025, 10:36 AM UTC (7087ea6)">Diff</a>
> chore: fix markup errors for the automatic publication
